<?php
global $post;
get_header();
echo '<div class="single">';
	echo '<article class="post readable">';
		$title = $post->post_title;
		$thumb = get_the_post_thumbnail_url( $post );
		$slug = $post->post_name;
		$link = '/tag/' . $slug;
		$id = $post->ID;
		$date = get_the_date();
		$content = $post->post_content;
		$content = apply_filters( 'the_content', $content );
		$content = str_replace( ']]>', ']]&gt;', $content );
		$stripped_content = strip_tags( $content );
		echo '<div class="top">';
			echo '<div class="info">';
				echo '<div class="title">';
					echo '<h1>' . $title . '</h1>';
				echo '</div>';
				echo '<div class="meta">';
					echo '<span>Published on ' . $date . '</span>';
					// echo '<span>' . str_word_count( $stripped_content ) . '</span>';
				echo '</div>';
			echo '</div>';
			echo '<div class="image">';
				echo '<img src="' . $thumb . '"/>';
			echo '</div>';
		echo '</div>';
		echo '<div class="text">';
			echo '<div class="content">';
				echo '<div class="max">';
					echo $content;
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</article>';
echo '</div>';
get_footer();
?>